# Generated by Django 2.2.28 on 2023-05-14 14:18
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('review', '0063_reporternidcountbycat'),
    ]

    operations = [
        migrations.CreateModel(
            name='YellowWordsMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('yellow_word', models.CharField(blank=True, max_length=100, null=True)),
                ('queue', models.CharField(blank=True, max_length=100, null=True)),
                ('dest_category', models.CharField(blank=True, max_length=100, null=True)),
                ('reject_reason_id', models.IntegerField(null=True)),
                ('total_count', models.IntegerField()),
                ('used_solo', models.IntegerField()),
                ('used_set', models.FloatField()),
                ('accepted', models.IntegerField()),
                ('accepted_solo', models.IntegerField()),
                ('accepted_set', models.FloatField()),
                ('related_rejected', models.IntegerField()),
                ('related_rejected_solo', models.IntegerField()),
                ('related_rejected_set', models.FloatField()),
                ('not_related_rejected', models.IntegerField()),
                ('not_related_rejected_solo', models.IntegerField()),
                ('not_related_rejected_set', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'yellow_word', 'queue', 'dest_category', 'reject_reason_id')},
            },
        ),
    ]